
ReadPopulationSimOutputSpecifications <- list(
  #Level of geography module is applied at
  RunBy = "Region",
  #Specify new tables to be created by Inp if any
  NewInpTable = items(
    item(
      TABLE = "Household",
      GROUP = "Global"
    ),
    item(
      TABLE = "Person",
      GROUP = "Global"
    )
  ),
  #Specify new tables to be created by Set if any
  NewSetTable = items(
    item(
      TABLE = "Household",
      GROUP = "Year"
    ),
    item(
      TABLE = "Person",
      GROUP = "Year"
    )
  ),
  #Specify input data
Inp = items(
	items(
		NAME = "household_id",
		FILE = "synthetic_households.csv",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "ID",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		SIZE =  0,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "Unique household ID generated by PopulationSim"
),
	items(
		NAME = "PUMA",
		FILE = "synthetic_households.csv",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "ID",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		SIZE =  0,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "PUMA regions associated with households"
),
	items(
		NAME = "TRACT",
		FILE = "synthetic_households.csv",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		SIZE = 21,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "TRACT regions associated with households"
),
	items(
		NAME = "BG",
		FILE = "synthetic_households.csv",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		SIZE = 21,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "BG regions associated with households"
),
	items(
		NAME = "hh_id",
		FILE = "synthetic_households.csv",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "ID",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		SIZE =  0,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "Unique household id as observed in the seed data"
),
	items(
		NAME = "NP",
		FILE = "synthetic_households.csv",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "category",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 1", ">9"),
		ISELEMENTOF = c(1:9),
		SIZE =  0,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "Number of people in the household"
),
	items(
		NAME = "NW",
		FILE = "synthetic_households.csv",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "category",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0", ">3"),
		ISELEMENTOF = c(0:3),
		SIZE =  0,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "Number of workers in the household"
),
	items(
		NAME = "HTYPE",
		FILE = "synthetic_households.csv",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "character",
		UNITS = "category",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = c("SF", "MF", "MH", "DUP"),
		SIZE =  3,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "Household residential type"
),
	items(
		NAME = "HHINCADJ",
		FILE = "synthetic_households.csv",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "currency",
		UNITS = "USD",
		NAVALUE = "",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		SIZE =  0,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "Household adjusted income"
),
	items(
		NAME = "household_id",
		FILE = "synthetic_persons.csv",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "ID",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		SIZE =  0,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "Unique household ID associated with person as generated by PopulationSim"
),
	items(
		NAME = "PUMA",
		FILE = "synthetic_persons.csv",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "ID",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		SIZE =  0,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "PUMA regions associated with persons"
),
	items(
		NAME = "TRACT",
		FILE = "synthetic_persons.csv",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		SIZE = 21,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "TRACT regions associated with persons"
),
	items(
		NAME = "BG",
		FILE = "synthetic_persons.csv",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		SIZE = 21,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "BG regions associated with persons"
),
	items(
		NAME = "per_num",
		FILE = "synthetic_persons.csv",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "ID",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		SIZE =  0,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "Persons ID within a household as generated by PopulationSim"
),
	items(
		NAME = "AGEP",
		FILE = "synthetic_persons.csv",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "time",
		UNITS = "YR",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		SIZE =  0,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "Age of a person"
),
	items(
		NAME = "RAC1P",
		FILE = "synthetic_persons.csv",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "category",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 1", ">9"),
		ISELEMENTOF = c(1:9),
		SIZE =  0,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "Race of a person"
),
	items(
		NAME = "PINCADJ",
		FILE = "synthetic_persons.csv",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "currency",
		UNITS = "USD",
		NAVALUE = "",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		SIZE =  0,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "Personal adjusted income"
),
	items(
		NAME = "WORKER",
		FILE = "synthetic_persons.csv",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "binary",
		NAVALUE = "",
		PROHIBIT = c("<0", ">1"),
		ISELEMENTOF = c(0,1),
		SIZE =  0,
		UNLIKELY = "",
		TOTAL = "",
		DESCRIPTION = "Flag for whether a person is a worker"
)
),
Get = items(
	items(
		NAME = "household_id",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "ID",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		SIZE =  0
),
	items(
		NAME = "PUMA",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "ID",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		SIZE =  0
),
	items(
		NAME = "TRACT",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		SIZE = 21
),
	items(
		NAME = "BG",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		SIZE = 21
),
	items(
		NAME = "hh_id",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "ID",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		SIZE =  0
),
	items(
		NAME = "NP",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "category",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 1", ">9"),
		ISELEMENTOF = c(1:9),
		SIZE =  0
),
	items(
		NAME = "NW",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "category",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0", ">3"),
		ISELEMENTOF = c(0:3),
		SIZE =  0
),
	items(
		NAME = "HTYPE",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "character",
		UNITS = "category",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = c("SF", "MF", "MH", "DUP"),
		SIZE =  3
),
	items(
		NAME = "HHINCADJ",
		TABLE = "Household",
		GROUP = "Global",
		TYPE = "currency",
		UNITS = "USD.2020",
		NAVALUE = "",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		SIZE =  0
),
	items(
		NAME = "household_id",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "ID",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		SIZE =  0
),
	items(
		NAME = "PUMA",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "ID",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		SIZE =  0
),
	items(
		NAME = "TRACT",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		SIZE = 21
),
	items(
		NAME = "BG",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		SIZE = 21
),
	items(
		NAME = "per_num",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "ID",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		SIZE =  0
),
	items(
		NAME = "AGEP",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "time",
		UNITS = "YR",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		SIZE =  0
),
	items(
		NAME = "RAC1P",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "category",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 1", ">9"),
		ISELEMENTOF = c(1:9),
		SIZE =  0
),
	items(
		NAME = "PINCADJ",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "currency",
		UNITS = "USD.2020",
		NAVALUE = "",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		SIZE =  0
),
	items(
		NAME = "WORKER",
		TABLE = "Person",
		GROUP = "Global",
		TYPE = "integer",
		UNITS = "binary",
		NAVALUE = "",
		PROHIBIT = c("<0", ">1"),
		ISELEMENTOF = c(0,1),
		SIZE =  0
)
),
Set = items(
	items(
		NAME = "NumHh",
		TABLE = "Azone",
		GROUP = "Year",
		TYPE = "households",
		UNITS = "HH",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Number of households (non-group quarters)"
),
	items(
		NAME = "NumGq",
		TABLE = "Azone",
		GROUP = "Year",
		TYPE = "people",
		UNITS = "PRSN",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Number of people in non-institutional group quarters"
),
	items(
		NAME = "NumWkr",
		TABLE = "Azone",
		GROUP = "Year",
		TYPE = "people",
		UNITS = "PRSN",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Number of workers residing in the zone"
),
	items(
		NAME = "HhId",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		DESCRIPTION = "Unique household ID"
),
	items(
		NAME = "Azone",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		DESCRIPTION = "Azone ID"
),
	items(
		NAME = "Bzone",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		DESCRIPTION = "Bzone ID"
),
	items(
		NAME = "Marea",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		DESCRIPTION = "Marea ID"
),
	items(
		NAME = "HhSize",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "people",
		UNITS = "PRSN",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Number of persons"
),
	items(
		NAME = "Age0to14",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "people",
		UNITS = "PRSN",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Persons in 0 to 14 year old age group"
),
	items(
		NAME = "Age15to19",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "people",
		UNITS = "PRSN",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Persons in 15 to 19 year old age group"
),
	items(
		NAME = "Age20to29",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "people",
		UNITS = "PRSN",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Persons in 20 to 29 year old age group"
),
	items(
		NAME = "Age30to54",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "people",
		UNITS = "PRSN",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Persons in 30 to 54 year old age group"
),
	items(
		NAME = "Age55to64",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "people",
		UNITS = "PRSN",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Persons in 55 to 64 year old age group"
),
	items(
		NAME = "Age65Plus",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "people",
		UNITS = "PRSN",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Persons in 65 or older age group"
),
	items(
		NAME = "HhType",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "character",
		UNITS = "category",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		DESCRIPTION = "Coded household age composition (e.g. 2-1-0-2-0-0) or Grp for group quarters"
),
	items(
		NAME = "Income",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "currency",
		UNITS = "USD.2020",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Total annual household (non-qroup & group quarters) income"
),
	items(
		NAME = "Wkr15to19",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "people",
		UNITS = "PRSN",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Persons in 0 to 14 year old age group"
),
	items(
		NAME = "Wkr20to29",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "people",
		UNITS = "PRSN",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Persons in 15 to 19 year old age group"
),
	items(
		NAME = "Wkr30to54",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "people",
		UNITS = "PRSN",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Persons in 20 to 29 year old age group"
),
	items(
		NAME = "Wkr55to64",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "people",
		UNITS = "PRSN",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Persons in 30 to 54 year old age group"
),
	items(
		NAME = "Wkr65Plus",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "people",
		UNITS = "PRSN",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Persons in 55 to 64 year old age group"
),
	items(
		NAME = "Workers",
		TABLE = "Household",
		GROUP = "Year",
		TYPE = "people",
		UNITS = "PRSN",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Persons in 65 or older age group"
),
	items(
		NAME = "PerId",
		TABLE = "Person",
		GROUP = "Year",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		DESCRIPTION = "Unique person ID"
),
	items(
		NAME = "HhId",
		TABLE = "Person",
		GROUP = "Year",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		DESCRIPTION = "Unique household ID"
),
	items(
		NAME = "Azone",
		TABLE = "Person",
		GROUP = "Year",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		DESCRIPTION = "Azone ID"
),
	items(
		NAME = "Bzone",
		TABLE = "Person",
		GROUP = "Year",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		DESCRIPTION = "Bzone ID"
),
	items(
		NAME = "Marea",
		TABLE = "Person",
		GROUP = "Year",
		TYPE = "character",
		UNITS = "ID",
		NAVALUE = "NA",
		PROHIBIT = c(""),
		ISELEMENTOF = "",
		DESCRIPTION = "Marea ID"
),
	items(
		NAME = "Age",
		TABLE = "Person",
		GROUP = "Year",
		TYPE = "time",
		UNITS = "YR",
		NAVALUE = "NA",
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Age of a person"
),
	items(
		NAME = "Income",
		TABLE = "Person",
		GROUP = "Year",
		TYPE = "currency",
		UNITS = "USD.2020",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = "",
		DESCRIPTION = "Total annual personal income"
),
	items(
		NAME = "Worker",
		TABLE = "Person",
		GROUP = "Year",
		TYPE = "integer",
		UNITS = "binary",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0",">1"),
		ISELEMENTOF = c(0,1),
		DESCRIPTION = "Flag for person as a worker"
),
	items(
		NAME = "Race",
		TABLE = "Person",
		GROUP = "Year",
		TYPE = "integer",
		UNITS = "category",
		NAVALUE = -1,
		PROHIBIT = c("NA", "< 0"),
		ISELEMENTOF = c(1:9),
		DESCRIPTION = "Coded race of a person (PUMS 2020 definition)"
)
)
)


#Save the data specifications list
#---------------------------------

#' Specifications list for ReadPopulationSimOutput module
#'
#' A list containing specifications for the ReadPopulationSimOutput module.
#'
#' @format A list containing 5 components:
#' \describe{
#'  \item{RunBy}{the level of geography that the module is run at}
#'  \item{NewSetTable}{new table to be created for datasets specified in the
#'  'Set' specifications}
#'  \item{Inp}{scenario input data to be loaded into the datastore for this
#'  module}
#'  \item{Get}{module inputs to be read from the datastore}
#'  \item{Set}{module outputs to be written to the datastore}
#' }
#' @source ReadPopulationSimOutput.R script.
"ReadPopulationSimOutputSpecifications"
visioneval::savePackageDataset(ReadPopulationSimOutputSpecifications, overwrite = TRUE)


#Main module function that reads PopulationSim output
#------------------------------------------------------
#' Main module function to reads PopulationSim output
#'
#' \code{ReadPopulationSimOutput} reads and stores the synthetic households and
#' persons produced by running PopulationSim in the VisionEval framework.
#'
#' @param L A list containing the components listed in the Get specifications
#' for the module.
#' @return A list containing the components specified in the Set
#' specifications for the module along with:
#' LENGTH: A named integer vector having a single named element, "Household",
#' which identifies the length (number of rows) of the Household table to be
#' created in the datastore.
#' SIZE: A named integer vector having two elements. The first element, "Azone",
#' identifies the size of the longest Azone name. The second element, "HhId",
#' identifies the size of the longest HhId.
#' @import visioneval data.table
#' @name ReadPopulationSimOutput
#' @export
ReadPopulationSimOutput <- function(L){
  #fix seed as synthesis involves sampling
  set.seed(L$G$Seed)
  #Define dimension name vectors
  Az <- as.vector(L$Year$Azone$Azone)
  Ag_ <- c("Age0to14", "Age15to19", "Age20to29", "Age30to54", "Age55to64", "Age65Plus")
  Ages_ <- c(-0.1, 15, 20, 30, 55, 65, Inf)
  
  # Create Ouptut list
  Out_ls <- initDataList()
  
  syn_hh_dt <- as.data.table(L$Global$Household)
  syn_per_dt <- as.data.table(L$Global$Person)
  ve_geo_dt <- as.data.table(L$G$Geo_df)
  
  ve_hh_dt <- data.table(
    HhId = syn_hh_dt[, household_id],
    HhSize = syn_hh_dt[, NP],
    Workers = syn_hh_dt[,NW],
    Bzone = syn_hh_dt[, paste0("D", BG)],
    Azone = ve_geo_dt[,Azone][match(syn_hh_dt[,paste0("D", BG)], ve_geo_dt[,Bzone])],
    Marea = ve_geo_dt[,Marea][match(syn_hh_dt[,paste0("D", BG)], ve_geo_dt[,Bzone])],
    Income = syn_hh_dt[,HHINCADJ]
  )
  
  ve_hh_dt[, HhId:=paste0(Azone, "-", HhId)]
  
  ve_per_dt <- data.table(
    PerId = syn_per_dt[,paste0(household_id, "-", per_num)],
    HhId = syn_per_dt[, household_id],
    Age = syn_per_dt[, AGEP],
    Race = syn_per_dt[, RAC1P],
    Income = syn_per_dt[, PINCADJ],
    Worker = syn_per_dt[, WORKER],
    Bzone = syn_per_dt[, paste0("D", BG)],
    Azone = ve_geo_dt[,Azone][match(syn_per_dt[,paste0("D", BG)], ve_geo_dt[,Bzone])],
    Marea = ve_geo_dt[,Marea][match(syn_per_dt[,paste0("D", BG)], ve_geo_dt[,Bzone])]
  )
  
  ve_per_dt[, HhId:=paste0(Azone, "-", HhId)]
  ve_per_dt[, PerId:=paste0(Azone, "-", PerId)]
  
  # Find Age Group
  ve_per_dt[,AgeGrp:=cut(Age, Ages_, labels=Ag_, include.lowest=FALSE)]
  
  age_dt <- dcast.data.table(ve_per_dt, HhId~AgeGrp,fun.aggregate = length)
  ve_hh_dt <- age_dt[ve_hh_dt,on=.(HhId)]
  
  # Household Type
  hhtype_dt <- age_dt[,.(HhId, HhType=apply(.SD,1,paste0,collapse="-")),
                      .SDcols=!"HhId"]
  ve_hh_dt <- hhtype_dt[ve_hh_dt,on=.(HhId)]
  
  # Find Worker in age group
  wrk_dt <- dcast.data.table(ve_per_dt, HhId~AgeGrp, value.var = "Worker",
                             fun.aggregate = sum)
  setnames(wrk_dt, gsub("Age", "Wkr", names(wrk_dt)))
  wrk_dt[,Wkr0to14:=NULL]
  ve_hh_dt <- wrk_dt[ve_hh_dt,on=.(HhId)]
  
  # Azone summaries
  azone_dt <- ve_hh_dt[,.(
    NumHh=.N,
    NumGq=0,
    NumWkr=sum(Workers)
  ),keyby=.(Azone)]
  
  # Create output list
  # Azone list
  Out_ls$Year$Azone <- list(
    NumHh = azone_dt[.(Az), NumHh],
    NumGq = azone_dt[.(Az), NumGq],
    NumWkr = azone_dt[.(Az), NumWkr]
  )
  # Household list
  Out_ls$Year$Household <- as.list(ve_hh_dt)
  
  # Person list
  ve_per_dt[,AgeGrp:=NULL]
  Out_ls$Year$Person <- as.list(ve_per_dt)
  
  #Calculate LENGTH attribute for Household table
  attributes(Out_ls$Year$Household)$LENGTH <-
    length(Out_ls$Year$Household$HhId)
  #Calculate SIZE attributes for 'Household$Azone' and 'Household$HhId'
  attributes(Out_ls$Year$Household$Azone)$SIZE <-
    max(nchar(Out_ls$Year$Household$Azone))
  attributes(Out_ls$Year$Household$Bzone)$SIZE <-
    max(nchar(Out_ls$Year$Household$Bzone))
  attributes(Out_ls$Year$Household$Marea)$SIZE <-
    max(nchar(Out_ls$Year$Household$Marea))
  attributes(Out_ls$Year$Household$HhId)$SIZE <-
    max(nchar(Out_ls$Year$Household$HhId))
  attributes(Out_ls$Year$Household$HhType)$SIZE <-
    max(nchar(Out_ls$Year$Household$HhType))
  
  #Calculate LENGTH attribute for Person table
  attributes(Out_ls$Year$Person)$LENGTH <-
    length(Out_ls$Year$Person$PerId)
  #Calculate SIZE attributes for 'Person$Azone' and 'Person$HhId'
  attributes(Out_ls$Year$Person$Azone)$SIZE <-
    max(nchar(Out_ls$Year$Person$Azone))
  attributes(Out_ls$Year$Person$Bzone)$SIZE <-
    max(nchar(Out_ls$Year$Person$Bzone))
  attributes(Out_ls$Year$Person$Marea)$SIZE <-
    max(nchar(Out_ls$Year$Person$Marea))
  attributes(Out_ls$Year$Person$HhId)$SIZE <-
    max(nchar(Out_ls$Year$Person$HhId))
  attributes(Out_ls$Year$Person$PerId)$SIZE <-
    max(nchar(Out_ls$Year$Person$PerId))
  #Return the list
  Out_ls
}
